### test router
GET http://localhost:4000/test

### create user
POST http://localhost:4000/users/register
Content-Type: application/json

{
  "name": "Rudi Kurniawan",
  "email": "rudikurniawan503@gmail.com",
  "password": "kurniawan",
  "passwordConfirmation": "kurniawan"
}